package com.chunchiehliang.navigationsample.utils

object RandomNames {
    private val names = listOf(
        "Wei",
        "Amiga",
        "Dirty Harry",
        "Midge",
        "Braniac",
        "Fattykins",
        "Bacon",
        "Monkey",
        "Amigo",
        "Ami",
        "Lulu",
        "Kirby",
        "Sport",
        "Donut",
        "Schnookums",
        "Junior",
        "Twiggy",
        "Beetle",
        "Goon",
        "Cindy",
        "Tart",
        "Rumplestiltskin",
        "Red Hot",
        "Halfling",
        "Doll",
        "Foxy Mama",
        "Mustache",
        "Scout",
        "Doctor",
        "Coke Zero",
        "Conductor",
        "Amazon",
        "Chiquita",
        "Hot Pepper",
        "Twizzler",
        "Genius",
        "Boomer",
        "Dolly",
        "Queenie",
        "Dino",
        "Snoopy",
    )

    fun getName() = names.random()
}